### ISSUE TITLE
This doesn't work on Developer Edition or Nightly.

### ISSUE THREAD

**Issue by Shugabuga** [uintdev/Firefox-Browser-Identifier#1]
This does not work on some builds of Firefox, as the given asset is not able to be found.

<img width="361" src="https://user-images.githubusercontent.com/10801851/38474146-c03bd74e-3b68-11e8-9e18-75561ef398c3.png">

Edit: Referring to `chrome://branding/content/icon64.png` solves the problem.

**Comment by uintdev** [comment]
Resolved in commit 5a94a4e4ad78bac4e9488a5bc4aefb7a0f4c7c42. Thanks.
